name: Deploy Test

on:
  push:
    branches:
      - main # 只在main上push触发部署
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v3 # 第一步，下载代码仓库

